### ISSUE TITLE
Some improvements =)

### ISSUE THREAD

**Issue by dracony** [dotink/inkwell-framework#1]
Hey, I was looking through the framework and have some thoughts/ideas:

1) Is there any reason why the index.php file is missing? I know it's stated in the docs that it's |easy to add one", but why?

2) Is Check Syntax.php really needed? 

3) Core.php class seems to be doing a bit too much. Setting a write directory and executing callbacks seem to be distinct enough things to be in different classes.

4) constants.php with global constants is a bit of an antipattern. Constants are much better of being class constants inside classes to which they relate the most.

5) kudos for having negotiators =)

6) I think you're overusing undocumentable arrays and callbacks a bit: `create(['core'], function($app, $broker),,,`

Haven't had a closer look yet =) Will write more later

**Comment by mattsah** [comment]
1) The `index.php` file is provided by the `inkwell-routing` package, since it uses the router directly.  If you install inkwell-routing, it will be copied to `public`.  I should probably mention this where I say that there isn't one in the docs.

2) No, but is it really not needed?  I just have one of those on pretty much all my packages whether they have additional tests or not.

3) I'm open to suggestions on how/why this should change *other than* due to OOP puritism, but I don't see a real benefit to splitting it.  `Core` is the application deals with the most basic app concerns (relative app root directory lookups, running the app clode, and checking basic information about the app environment and state).  I realize this is more than one responsibility, so what?

4) See #3.  I'm open to any actual arguments as to why this is a bad idea, what problems it may cause, why I might want to break them up over respected classes, etc.  But simply stating that something is an antipattern and lacks technical purity doesn't put forward an argument.  It's like saying, "I'm right because I said I'm right."

5) Thanks, also thank @willdurand for providing a clean standalone library.

6) I'd consider this a documentation issue, although the example you provide is related to affinity, which is documented, there's probably a little bit better docs here https://github.com/dotink/affinity than what is on the inKWell nano core docs, so I'll open a ticket specific to that.

Thanks for all the feedback.

I think the overall things I gather are:

- It probably needs to be made clearer that certain things are provided by additional components, but that depending on how you're using the framework (such as just the nano core), they aren't going to be there.

- People are concerned with strict OOP / SOLID adherance.  Although I strive to make inKWell incorporate all best practices, one of the things that I aim to do is to keep it a lot simpler and straightforward *internally* then something like Symfony or Laravel.  This will, on occassion deal with viewing things in terms of broader responsibilities.  I have no problem with this when the responsibilities are logically grouped, and do not impose additional burden on developers trying to use one without influencing the other.

- There remains a lot of specific documentation issues.  It's more helpful to provide these in the form of a question with specific links to where you saw it or would have expected it, i.e.:  "I was looking at <link> and saw the example such as `...`, what does the first parameter do?"

Again, I appreciate all of the feedback, please don't take my disagreement as lack of appreciation and please don't take #3 or #4 as being confrontational, I'm just more interested in reasonable justification than I am in authoritative claims coming from OOP purity blogs.

**Comment by mattsah** [comment]
Closing this, as I've wrapped up the sub-issues created around it and there has been no further discussion.
